<?php

/*
 * @package     Sole-node
 * @author      <"neohex">

 */

function sole_node_node_insert($node) {
  _sole_node_make_node_alone_at_front_page($node);
}

function sole_node_node_update($node) {
  _sole_node_make_node_alone_at_front_page($node);
}


function _sole_node_make_node_alone_at_front_page($node) {
  if ($node->promote) {
    db_query('UPDATE node SET promote = 0 WHERE nid != :nid', ['nid' => $node->nid]);
    db_query('UPDATE node_revision SET promote = 0 WHERE nid != :nid', ['nid' => $node->nid]);
  }
}
